version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Maps port 80 in the container to port 8080 on the host
    restart: always # Ensures the container restarts if it crashes
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Optional: Use if you have a custom Nginx config
    environment:
      NODE_ENV: production
