name: Deploy to Dokploy

on:
  push:
    branches:
      - main  # Adjust to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Dokploy Deployment
        run: |
          curl -X POST https://dokploy.kalindimarketing.com/api/deploy/jH3OwltiRwEsfBvwSMu6U
